# version: '3.8'

# services:
#   postgres:
#     image: postgres:15
#     container_name: app_postgres
#     environment:
#       POSTGRES_USER: boris
#       POSTGRES_PASSWORD: 123
#       POSTGRES_DB: postgres
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U boris -d postgres"]
#       interval: 5s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data:

version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: app_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}  # Default fallback
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}  # Never hardcode
      POSTGRES_DB: ${DB_NAME:-app_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-app_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: